### ISSUE TITLE
Prusa Research AVR Boards devel

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Arduino_Boards#2]
Update on my development to combine boards used by Prusa
Hi @DRracer @mkbel
I thought it might be more useful to open an issue instead adding comments to https://github.com/prusa3d/Arduino_Boards/pull/1
So what happend
- I started another branch (may have to rename it later) https://github.com/3d-gussner/Arduino_Boards/tree/V1.0.2_merged_boards
  - pursa_mm_control and EinsyRambo boards are in one definition
  - bootloaders for both are included
    - @mkbel still don't know why there is a different avrdude.conf for the pursa_mm_control board
   - Still didn't get an answer why  `-P{serial.port}` and `"-P{serial.port}"` are different in the `platform.txt` for MMU and Einsy?
   - EinsyRAMBo specific `compiler.c.elf.extra_flags=-Wl,-u,vfprintf -lprintf_flt -lm` are added to the `boards.txt` part and it seams to work fine. 1st tests where successful and debug log showed that these were used while compiling it in `PF-build.sh` as well in fresh `Arduino IDE 1.8.5 portable versions` ... tests with IDE 1.8.9 will come later
- Still struggle to get the `avr6.xn` patch into the definition but
   - as users using own Arduino IDE build environment are asked to change to primary language only in `config.h` it isn't needed here
   - If somebody whats to build their own multiple language versions they will not struggle to add the `avr6.xn` patch as they have to deal with the poorly documented language build.
   - and for `PF-build.sh` users we just patch it as it is now.

Can you have a look and give me some feedback?

**Comment by mkbel** [comment]
If you managed to get both boards into one board manager this would be awesome. Please open pull request for that change.

**Comment by 3d-gussner** [comment]
@mkbel Can you give me an answer for my questions above?

- still don't know why there is a different `avrdude.conf` for the `pursa_mm_control board`
- why are -P{serial.port} and "-P{serial.port}" different in the `platform.txt` for MMU and Einsy?

@DRracer and @mkbel 
Also updated few things in https://github.com/3d-gussner/Arduino_Boards/tree/V1.0.2_merged_boards 

Would be great if you could give some feedback.

**Comment by DRracer** [comment]
@3d-gussner regarding your questions - I don't know, but I'll try to find out asking a few more people. May be someone remembers ;)
Btw. excelent piece of work, I really love all the documentation you put together.

**Comment by 3d-gussner** [comment]
@DRracer Thanks for having a look.

Meanwhile i found https://github.com/prusa3d/PrusaSlicer/blob/master/src/avrdude/avrdude-slic3r.conf 

As the PrusaSlicer can upload firmware correctly to the Einsy, miniRAMBo and Prusa_mm_controler I was thinking to use that specific one also here.
I also added the Einsy/miniRAMBo bootloader from https://github.com/prusa3d/stk500v2-prusa and that works fine.

Maybe the PrusaSlicer team can give you some answers about `why are -P{serial.port} and "-P{serial.port}" different in the platform.txt for MMU and Einsy?`

Do you agree with the naming convention?
Would it make sense to move few parts from the README.MD to the Wiki?

**Comment by 3d-gussner** [comment]
Update: I made a PR https://github.com/DRracer/Arduino_Boards/pull/4

Open task is to use the Prusa Slicer avrdude version ...
