### ISSUE TITLE
there are 2 entries in Arduino Boards Manager, what should I take?

### ISSUE THREAD

**Issue by 3Dietrich** [prusa3d/Arduino_Boards#7]
There are 2 entries in Arduino Board Manager:
"Prusa research AVR Boards" and
"Prusa research AVR MK3/MK3S Einsy RAMBo"

Both point to my printer (MK3S). One has additionally  the MMU upgrade with it, which I don't need, but the current version is higher (1.0.3) ..I don't want to bombard my printer with the wrong code, so I'm asking here:

As i3 MK3S user (without MMU), which of the two boards should I use? The newer version or the more fitting name?
And I ask (if you haven't already done so and I just didn't get it): Could you add an info so that no one need to ask again...
<img width="796" alt="screenshot 2020-08-15" src="https://user-images.githubusercontent.com/4608796/90311587-a33c8a00-defc-11ea-9553-111bcc1065a3.png">

**Comment by 3Dietrich** [comment]
As i3 MK3S user (without MMU), which of the two boards should I use?

**Comment by wavexx** [comment]
Mmh, looks like nobody ever noticed this issue here.
@3d-gussner is it really expected to have more than one entry?
Looks like the first one contains all the boards.

**Comment by 3d-gussner** [comment]
@3Dietrich Sorry that it is confusing. We changed at some point the naming and kept the previous for older firmware versions active.
I will make a note to remove the old one in of the next versions, hoping nobody will try to compile a very old version of the firmware.

Please use `Prusa Research AVR Boards` as this will contain at some point all avr based boards
- miniRAMBo
- Einsy
- MMU2 control board
- _CW1 control board_
- _other AVR based boards_

Hope that answers your question. If so please consider to close this issue.

**Comment by leptun** [comment]
You can change the name of the old board definition so it has `(deprecated)` in its name. Example board definition that I've seen in the wild:
![image](https://user-images.githubusercontent.com/17808203/176025708-84734be8-f6c0-47d4-831e-3274cfa5888e.png)

**Comment by 3Dietrich** [comment]
haha.. better 2 years later than never :)
thank you

**Comment by 3d-gussner** [comment]
@3Dietrich Solved with https://github.com/prusa3d/Arduino_Boards/pull/18
Please consider closing this issue.
